### PR TITLE
Fix/3

### PR DESCRIPTION
**Pull request by zhaoyuango**
# Description
Fix issue #3

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
code was removed and unit tests updated

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warning**Test Configuration**:
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jjzazuet** [comment]
Hey @zhaoyuango , did you update the project version number? Thanks!

**Review by jjzazuet — CHANGES_REQUESTED** [review]
Looks good overall. Please update project version and we should be good. Thanks!

**Comment by zhaoyuango** [comment]
Hey I have updated project version number. thanks

**Review by jjzazuet — APPROVED** [review]
LGTM (looks good to me).

**Pull request merged**
